### PR TITLE
Merged the scripts into two files

### PR DESCRIPTION
**Pull request by Misko-2083**
A single password entry is now required
Less dialogs

### CODE REVIEW

**Comment by linuxlite** [comment]
I like this misko, really good stuff :smile: I'll put this through testing and try to get back to you soon.

**Comment by linuxlite** [comment]
See PM on Forums for one more addition.

**Comment by Misko-2083** [comment]
All right, added a dialog at the end.

**Comment by linuxlite** [comment]
Thanks for the end dialogue. Choose default Browser part does not work.

**Comment by Misko-2083** [comment]
fixed in the patch-1 branch

**Comment by linuxlite** [comment]
Choose default Browser tested, working. Thank you.

**Pull request merged**
